/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as FaucetRouteImport } from './routes/faucet'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiceIndexRouteImport } from './routes/dice/index'
import { Route as MarketsMarketIdRouteImport } from './routes/markets/$marketId'
import { Route as DiceCommitmentIdRouteImport } from './routes/dice/$commitmentId'

const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const FaucetRoute = FaucetRouteImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiceIndexRoute = DiceIndexRouteImport.update({
  id: '/dice/',
  path: '/dice/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsMarketIdRoute = MarketsMarketIdRouteImport.update({
  id: '/markets/$marketId',
  path: '/markets/$marketId',
  getParentRoute: () => rootRouteImport,
} as any)
const DiceCommitmentIdRoute = DiceCommitmentIdRouteImport.update({
  id: '/dice/$commitmentId',
  path: '/dice/$commitmentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/faucet': typeof FaucetRoute
  '/orders': typeof OrdersRoute
  '/positions': typeof PositionsRoute
  '/dice/$commitmentId': typeof DiceCommitmentIdRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/dice/': typeof DiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/faucet': typeof FaucetRoute
  '/orders': typeof OrdersRoute
  '/positions': typeof PositionsRoute
  '/dice/$commitmentId': typeof DiceCommitmentIdRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/dice': typeof DiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/faucet': typeof FaucetRoute
  '/orders': typeof OrdersRoute
  '/positions': typeof PositionsRoute
  '/dice/$commitmentId': typeof DiceCommitmentIdRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/dice/': typeof DiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/faucet'
    | '/orders'
    | '/positions'
    | '/dice/$commitmentId'
    | '/markets/$marketId'
    | '/dice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/faucet'
    | '/orders'
    | '/positions'
    | '/dice/$commitmentId'
    | '/markets/$marketId'
    | '/dice'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/faucet'
    | '/orders'
    | '/positions'
    | '/dice/$commitmentId'
    | '/markets/$marketId'
    | '/dice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  FaucetRoute: typeof FaucetRoute
  OrdersRoute: typeof OrdersRoute
  PositionsRoute: typeof PositionsRoute
  DiceCommitmentIdRoute: typeof DiceCommitmentIdRoute
  MarketsMarketIdRoute: typeof MarketsMarketIdRoute
  DiceIndexRoute: typeof DiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faucet': {
      id: '/faucet'
      path: '/faucet'
      fullPath: '/faucet'
      preLoaderRoute: typeof FaucetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dice/': {
      id: '/dice/'
      path: '/dice'
      fullPath: '/dice/'
      preLoaderRoute: typeof DiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$marketId': {
      id: '/markets/$marketId'
      path: '/markets/$marketId'
      fullPath: '/markets/$marketId'
      preLoaderRoute: typeof MarketsMarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dice/$commitmentId': {
      id: '/dice/$commitmentId'
      path: '/dice/$commitmentId'
      fullPath: '/dice/$commitmentId'
      preLoaderRoute: typeof DiceCommitmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  FaucetRoute: FaucetRoute,
  OrdersRoute: OrdersRoute,
  PositionsRoute: PositionsRoute,
  DiceCommitmentIdRoute: DiceCommitmentIdRoute,
  MarketsMarketIdRoute: MarketsMarketIdRoute,
  DiceIndexRoute: DiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
