import * as fs from "fs";
import * as path from "path";
import type { HardhatRuntimeEnvironment } from "hardhat/types";

const CONTRACT_TO_ENV: Record<string, string> = {
  TABcoin: "VITE_TABCOIN_ADDRESS",
  ConditionalTokens: "VITE_CONDITIONAL_TOKENS_ADDRESS",
  PredictionMarketV2: "VITE_PREDICTION_MARKET_ADDRESS",
  PositionWrapperFactory: "VITE_POSITION_WRAPPER_FACTORY_ADDRESS",
  TabClob: "VITE_TABCLOB_ADDRESS",
};

// Path from packages/hardhat/ to apps/web/
const WEB_DIR = path.resolve(__dirname, "../../../../web");

export default async function generateWebEnv(hre: HardhatRuntimeEnvironment): Promise<void> {
  const chainId = await hre.getChainId();
  if (chainId !== "31337") {
    console.log(`⏭  Skipping web .env.local generation on chainId=${chainId}.`);
    return;
  }

  const deploymentsDir = path.resolve(__dirname, "..", "deployments", "localhost");
  if (!fs.existsSync(deploymentsDir)) {
    console.log("⚠  No localhost deployments found, skipping .env.local generation.");
    return;
  }

  const lines: string[] = [
    "# Auto-generated by yarn deploy — do not edit manually",
    `VITE_CHAIN_ID=${chainId}`,
  ];

  for (const [contractName, envVar] of Object.entries(CONTRACT_TO_ENV)) {
    const file = path.join(deploymentsDir, `${contractName}.json`);
    if (fs.existsSync(file)) {
      const { address } = JSON.parse(fs.readFileSync(file, "utf-8"));
      lines.push(`${envVar}=${address}`);
    } else {
      console.log(`⚠  ${contractName}.json not found, skipping ${envVar}`);
    }
  }

  const envPath = path.join(WEB_DIR, ".env.local");
  fs.writeFileSync(envPath, lines.join("\n") + "\n");
  console.log(`📝 Updated ${envPath}`);
}