/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    ConditionalTokens: {
      address: "0x05fa1e1EE3249C26db881930F0bF2cb1fe05da98",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
          ],
          name: "AddressEmptyCode",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "AddressInsufficientBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "ERC1155InsufficientBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "approver",
              type: "address",
            },
          ],
          name: "ERC1155InvalidApprover",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "idsLength",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "valuesLength",
              type: "uint256",
            },
          ],
          name: "ERC1155InvalidArrayLength",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "ERC1155InvalidOperator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
          ],
          name: "ERC1155InvalidReceiver",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "ERC1155InvalidSender",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "ERC1155MissingApprovalForAll",
          type: "error",
        },
        {
          inputs: [],
          name: "FailedInnerCall",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "SafeERC20FailedOperation",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "ApprovalForAll",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "oracle",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "questionId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "outcomeSlotCount",
              type: "uint256",
            },
          ],
          name: "ConditionPreparation",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "oracle",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "questionId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "outcomeSlotCount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "payoutNumerators",
              type: "uint256[]",
            },
          ],
          name: "ConditionResolution",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "redeemer",
              type: "address",
            },
            {
              indexed: true,
              internalType: "contract IERC20",
              name: "collateralToken",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "indexSets",
              type: "uint256[]",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "payout",
              type: "uint256",
            },
          ],
          name: "PayoutRedemption",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "stakeholder",
              type: "address",
            },
            {
              indexed: false,
              internalType: "contract IERC20",
              name: "collateralToken",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "partition",
              type: "uint256[]",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "PositionSplit",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "stakeholder",
              type: "address",
            },
            {
              indexed: false,
              internalType: "contract IERC20",
              name: "collateralToken",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "partition",
              type: "uint256[]",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "PositionsMerge",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "ids",
              type: "uint256[]",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "values",
              type: "uint256[]",
            },
          ],
          name: "TransferBatch",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "TransferSingle",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "value",
              type: "string",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "URI",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "accounts",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "ids",
              type: "uint256[]",
            },
          ],
          name: "balanceOfBatch",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
          ],
          name: "conditionOracle",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "indexSet",
              type: "uint256",
            },
          ],
          name: "getCollectionId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "oracle",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "questionId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "outcomeSlotCount",
              type: "uint256",
            },
          ],
          name: "getConditionId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
          ],
          name: "getOutcomeSlotCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "contract IERC20",
              name: "collateralToken",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "collectionId",
              type: "bytes32",
            },
          ],
          name: "getPositionId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "isApprovedForAll",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
          ],
          name: "isResolved",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "contract IERC20",
              name: "collateralToken",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              internalType: "uint256[]",
              name: "partition",
              type: "uint256[]",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "mergePositions",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
          ],
          name: "payoutDenominator",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "i",
              type: "uint256",
            },
          ],
          name: "payoutNumerators",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "oracle",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "questionId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "outcomeSlotCount",
              type: "uint256",
            },
          ],
          name: "prepareCondition",
          outputs: [
            {
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "contract IERC20",
              name: "collateralToken",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              internalType: "uint256[]",
              name: "indexSets",
              type: "uint256[]",
            },
          ],
          name: "redeemPositions",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "questionId",
              type: "bytes32",
            },
            {
              internalType: "uint256[]",
              name: "payouts",
              type: "uint256[]",
            },
          ],
          name: "reportPayouts",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256[]",
              name: "ids",
              type: "uint256[]",
            },
            {
              internalType: "uint256[]",
              name: "values",
              type: "uint256[]",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "safeBatchTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "setApprovalForAll",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "contract IERC20",
              name: "collateralToken",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              internalType: "uint256[]",
              name: "partition",
              type: "uint256[]",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "splitPosition",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "uri",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {
        balanceOf: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
        balanceOfBatch: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
        isApprovedForAll: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
        safeBatchTransferFrom:
          "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
        safeTransferFrom: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
        setApprovalForAll: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
        supportsInterface: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
        uri: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
      },
      deployedOnBlock: 45723826,
    },
    PositionWrapper: {
      address: "0x5D343ee475E8960229136e03ebe1153D8605aD56",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "allowance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
          ],
          name: "ERC20InsufficientAllowance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
          ],
          name: "ERC20InsufficientBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "approver",
              type: "address",
            },
          ],
          name: "ERC20InvalidApprover",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
          ],
          name: "ERC20InvalidReceiver",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "ERC20InvalidSender",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
          ],
          name: "ERC20InvalidSpender",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidInitialization",
          type: "error",
        },
        {
          inputs: [],
          name: "NotInitializing",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint64",
              name: "version",
              type: "uint64",
            },
          ],
          name: "Initialized",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
          ],
          name: "allowance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "ct",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "name_",
              type: "string",
            },
            {
              internalType: "string",
              name: "symbol_",
              type: "string",
            },
            {
              internalType: "address",
              name: "ct_",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "positionId_",
              type: "uint256",
            },
          ],
          name: "initialize",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
            {
              internalType: "bytes",
              name: "",
              type: "bytes",
            },
          ],
          name: "onERC1155BatchReceived",
          outputs: [
            {
              internalType: "bytes4",
              name: "",
              type: "bytes4",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "",
              type: "bytes",
            },
          ],
          name: "onERC1155Received",
          outputs: [
            {
              internalType: "bytes4",
              name: "",
              type: "bytes4",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [],
          name: "positionId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "transfer",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "unwrap",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "wrap",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        allowance:
          "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol",
        approve:
          "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol",
        balanceOf:
          "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol",
        decimals:
          "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol",
        name: "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol",
        symbol:
          "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol",
        totalSupply:
          "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol",
        transfer:
          "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol",
        transferFrom:
          "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol",
        onERC1155BatchReceived:
          "@openzeppelin/contracts/token/ERC1155/IERC1155Receiver.sol",
        onERC1155Received:
          "@openzeppelin/contracts/token/ERC1155/IERC1155Receiver.sol",
        supportsInterface:
          "@openzeppelin/contracts/token/ERC1155/IERC1155Receiver.sol",
      },
      deployedOnBlock: 45723830,
    },
    PositionWrapperFactory: {
      address: "0x1e79FAc6B154B49101252C447E0e68a0a20fc3c0",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_wrapperImpl",
              type: "address",
            },
            {
              internalType: "address",
              name: "_ct",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "ERC1167FailedCreateClone",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "collateral",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "indexSet",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "positionId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "wrapper",
              type: "address",
            },
          ],
          name: "WrapperCreated",
          type: "event",
        },
        {
          inputs: [],
          name: "ct",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "collateral",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "indexSet",
              type: "uint256",
            },
          ],
          name: "getOrCreateWrapper",
          outputs: [
            {
              internalType: "address",
              name: "w",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "collateral",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "indexSet",
              type: "uint256",
            },
          ],
          name: "getWrapper",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "collateral",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "indexSet",
              type: "uint256",
            },
          ],
          name: "key",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [],
          name: "wrapperImpl",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "wrapperOf",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 45723832,
    },
    PredictionMarketV2: {
      address: "0x1157c1D6027A5f4Cd62682A7F0d1da426A4b65E3",
      abi: [
        {
          inputs: [
            {
              internalType: "contract IERC20",
              name: "_collateral",
              type: "address",
            },
            {
              internalType: "contract IConditionalTokens",
              name: "_ct",
              type: "address",
            },
            {
              internalType: "address",
              name: "_curator",
              type: "address",
            },
            {
              internalType: "address",
              name: "_governance",
              type: "address",
            },
            {
              internalType: "address",
              name: "_treasury",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_defaultBond",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_creatorCancelWindow",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
          ],
          name: "AddressEmptyCode",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "AddressInsufficientBalance",
          type: "error",
        },
        {
          inputs: [],
          name: "FailedInnerCall",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "SafeERC20FailedOperation",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "BondClaimed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "BondSlashed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previous",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "next",
              type: "address",
            },
          ],
          name: "CuratorTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previous",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "next",
              type: "address",
            },
          ],
          name: "GovernanceTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "by",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "bondSlashed",
              type: "bool",
            },
          ],
          name: "MarketCanceled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "enum PredictionMarketV2.OutcomeType",
              name: "outcomeType",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "outcomeSlotCount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "bondAmount",
              type: "uint256",
            },
          ],
          name: "MarketCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newExpiresAt",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newResolutionTime",
              type: "uint256",
            },
          ],
          name: "MarketExtended",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
          ],
          name: "MarketPaused",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "payouts",
              type: "uint256[]",
            },
          ],
          name: "MarketResolved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
          ],
          name: "MarketResumed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isVerified",
              type: "bool",
            },
          ],
          name: "MarketVerified",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "defaultBond",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "creatorCancelWindow",
              type: "uint256",
            },
          ],
          name: "ParamsUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previous",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "next",
              type: "address",
            },
          ],
          name: "TreasuryTransferred",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
          ],
          name: "cancelMarket",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
          ],
          name: "claimCreatorBond",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "collateral",
          outputs: [
            {
              internalType: "contract IERC20",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "category",
              type: "string",
            },
            {
              internalType: "enum PredictionMarketV2.OutcomeType",
              name: "outcomeType",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "outcomeSlotCount",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "oracle",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "resolutionTime",
              type: "uint256",
            },
          ],
          name: "createMarket",
          outputs: [
            {
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "creatorCancelWindow",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "ct",
          outputs: [
            {
              internalType: "contract IConditionalTokens",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "curator",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "defaultBond",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "newExpiresAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "newResolutionTime",
              type: "uint256",
            },
          ],
          name: "extendMarket",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
          ],
          name: "getMarket",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "oracle",
                  type: "address",
                },
                {
                  internalType: "bytes32",
                  name: "questionId",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "conditionId",
                  type: "bytes32",
                },
                {
                  internalType: "uint256",
                  name: "outcomeSlotCount",
                  type: "uint256",
                },
                {
                  internalType: "enum PredictionMarketV2.OutcomeType",
                  name: "outcomeType",
                  type: "uint8",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "category",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "expiresAt",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "resolutionTime",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "bondAmount",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "bondClaimed",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "bondSlashed",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "verified",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "canceled",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "resolved",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "paused",
                  type: "bool",
                },
              ],
              internalType: "struct PredictionMarketV2.Market",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "governance",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "marketCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "markets",
          outputs: [
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              internalType: "address",
              name: "oracle",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "questionId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "conditionId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "outcomeSlotCount",
              type: "uint256",
            },
            {
              internalType: "enum PredictionMarketV2.OutcomeType",
              name: "outcomeType",
              type: "uint8",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "category",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "createdAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "resolutionTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "bondAmount",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "bondClaimed",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "bondSlashed",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "verified",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "canceled",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "resolved",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "paused",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
          ],
          name: "pauseMarket",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
            {
              internalType: "uint256[]",
              name: "payouts",
              type: "uint256[]",
            },
          ],
          name: "resolveMarket",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
          ],
          name: "resumeMarket",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_defaultBond",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_creatorCancelWindow",
              type: "uint256",
            },
          ],
          name: "setParams",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
          ],
          name: "slashCreatorBond",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "next",
              type: "address",
            },
          ],
          name: "transferCurator",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "next",
              type: "address",
            },
          ],
          name: "transferGovernance",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "next",
              type: "address",
            },
          ],
          name: "transferTreasury",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "treasury",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isVerified",
              type: "bool",
            },
          ],
          name: "verifyMarket",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 45723828,
    },
    TabClob: {
      address: "0xb6Df8d192e0d8EFD03E248aeC59C37E55C5A9998",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
          ],
          name: "AddressEmptyCode",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "AddressInsufficientBalance",
          type: "error",
        },
        {
          inputs: [],
          name: "FailedInnerCall",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidShortString",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "SafeERC20FailedOperation",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "str",
              type: "string",
            },
          ],
          name: "StringTooLong",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [],
          name: "EIP712DomainChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "orderHash",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "maker",
              type: "address",
            },
          ],
          name: "OrderCanceled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "orderHash",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "maker",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "taker",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "makerToken",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "takerToken",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint128",
              name: "makerAmount",
              type: "uint128",
            },
            {
              indexed: false,
              internalType: "uint128",
              name: "takerAmount",
              type: "uint128",
            },
          ],
          name: "OrderFilled",
          type: "event",
        },
        {
          inputs: [],
          name: "DOMAIN_SEPARATOR",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "ORDER_TYPEHASH",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "maker",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "taker",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "makerToken",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "takerToken",
                  type: "address",
                },
                {
                  internalType: "uint128",
                  name: "makerAmount",
                  type: "uint128",
                },
                {
                  internalType: "uint128",
                  name: "takerAmount",
                  type: "uint128",
                },
                {
                  internalType: "uint64",
                  name: "expiry",
                  type: "uint64",
                },
                {
                  internalType: "uint256",
                  name: "salt",
                  type: "uint256",
                },
              ],
              internalType: "struct TabClob.Order",
              name: "o",
              type: "tuple",
            },
          ],
          name: "cancel",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "canceled",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "eip712Domain",
          outputs: [
            {
              internalType: "bytes1",
              name: "fields",
              type: "bytes1",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "version",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "chainId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "verifyingContract",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "salt",
              type: "bytes32",
            },
            {
              internalType: "uint256[]",
              name: "extensions",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "maker",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "taker",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "makerToken",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "takerToken",
                  type: "address",
                },
                {
                  internalType: "uint128",
                  name: "makerAmount",
                  type: "uint128",
                },
                {
                  internalType: "uint128",
                  name: "takerAmount",
                  type: "uint128",
                },
                {
                  internalType: "uint64",
                  name: "expiry",
                  type: "uint64",
                },
                {
                  internalType: "uint256",
                  name: "salt",
                  type: "uint256",
                },
              ],
              internalType: "struct TabClob.Order",
              name: "o",
              type: "tuple",
            },
            {
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
          ],
          name: "fill",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "filled",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "maker",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "taker",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "makerToken",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "takerToken",
                  type: "address",
                },
                {
                  internalType: "uint128",
                  name: "makerAmount",
                  type: "uint128",
                },
                {
                  internalType: "uint128",
                  name: "takerAmount",
                  type: "uint128",
                },
                {
                  internalType: "uint64",
                  name: "expiry",
                  type: "uint64",
                },
                {
                  internalType: "uint256",
                  name: "salt",
                  type: "uint256",
                },
              ],
              internalType: "struct TabClob.Order",
              name: "o",
              type: "tuple",
            },
          ],
          name: "hashOrder",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {
        eip712Domain: "@openzeppelin/contracts/utils/cryptography/EIP712.sol",
      },
      deployedOnBlock: 45723834,
    },
    TABcoin: {
      address: "0xf56DD038B0eC671AbEBAA6499fdd5b195Cf089e4",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "allowance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
          ],
          name: "ERC20InsufficientAllowance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
          ],
          name: "ERC20InsufficientBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "approver",
              type: "address",
            },
          ],
          name: "ERC20InvalidApprover",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
          ],
          name: "ERC20InvalidReceiver",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "ERC20InvalidSender",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
          ],
          name: "ERC20InvalidSpender",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "ClaimAuthorized",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "ClaimRevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Claimed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Minted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [],
          name: "AUTHORIZER",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "CLAIM_AMOUNT",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
          ],
          name: "allowance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "authorizeClaim",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "burn",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "burnFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "claim",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "claimAuthorized",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "claimConsumed",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "mint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "revokeClaim",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "transfer",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        allowance:
          "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol",
        approve:
          "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol",
        balanceOf:
          "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol",
        decimals:
          "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol",
        name: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol",
        symbol:
          "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol",
        totalSupply:
          "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol",
        transfer:
          "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol",
        transferFrom:
          "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol",
        burn: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol",
        burnFrom:
          "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol",
      },
      deployedOnBlock: 45723824,
    },
    YourContract: {
      address: "0x460663a7bF3679683727478aE6eAA138b0978941",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userGreetingCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 45723822,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
