"""add markets

Revision ID: 1e23c52420d1
Revises: 6f65dd0bfed2
Create Date: 2026-05-08 18:38:02.222529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e23c52420d1'
down_revision: Union[str, Sequence[str], None] = '6f65dd0bfed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=False),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rules', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('outcome_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('outcomes', sa.JSON(), nullable=False),
    sa.Column('scalar_min', sa.Float(), nullable=True),
    sa.Column('scalar_max', sa.Float(), nullable=True),
    sa.Column('scalar_unit', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('resolution_time', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condition_id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_markets_category'), 'markets', ['category'], unique=False)
    op.create_index(op.f('ix_markets_market_id'), 'markets', ['market_id'], unique=True)
    op.create_index(op.f('ix_markets_outcome_type'), 'markets', ['outcome_type'], unique=False)
    op.create_index(op.f('ix_markets_status'), 'markets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_markets_status'), table_name='markets')
    op.drop_index(op.f('ix_markets_outcome_type'), table_name='markets')
    op.drop_index(op.f('ix_markets_market_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_category'), table_name='markets')
    op.drop_table('markets')
    # ### end Alembic commands ###
