"""add market_id to orders

Revision ID: 3cf957fbbe15
Revises: 6f65dd0bfed2
Create Date: 2026-05-08 20:36:01.532185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3cf957fbbe15'
down_revision: Union[str, Sequence[str], None] = '6f65dd0bfed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('market_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_market_id'), 'orders', ['market_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_market_id'), table_name='orders')
    op.drop_column('orders', 'market_id')
    # ### end Alembic commands ###
